name: Deploy Code to GitHub

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install the gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 416.0.0'
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          export_default_credentials: true

      - name: Build and push the Docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          echo "Authenticating Docker with gcloud"
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev
          
          echo "Building the Docker image"
          docker build -t asia-southeast2-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/github-actions/golang:latest .
          
          echo "Pushing the Docker image"
          docker push asia-southeast2-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/github-actions/golang:latest